name: fluent_ui
description: Implements Windows UI in Flutter. Based on the official documentation
version: 4.9.0
homepage: https://bdlukaa.github.io/fluent_ui/#/
repository: https://github.com/bdlukaa/fluent_ui
issue_tracker: https://github.com/bdlukaa/fluent_ui/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

topics:
  - windows
  - desktop
  - ui
  - widgets

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Used on date and time pickers
  intl: '>=0.19.0 <= 1.0.0'

  # Used on TabView
  scroll_pos: '>=0.5.0 < 1.0.0'

  # Used on icon generator
  recase: ^4.1.0

  # Used on NumberBox
  math_expressions: ^2.4.0
  file_picker: ^6.1.1
  crop_your_image: ^0.7.5
  flutter_json_view: ^1.1.3
  http: ^1.1.0
  sqflite: ^2.3.0
  syncfusion_flutter_datagrid: ^23.1.44
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  intl_utils: ^2.8.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf
